---
title: "Doublet_removal"
author: "Camino RSM"
date: "2024-11-20"
output: html_document
---


# Removal of doublets in SARC dataset
```{r}
SARC_f_list = readRDS("/home/caminors/Desktop/sc_RNAseq/QC_seurats/SARC_f_list_SoupX.rds")
## find doublets on cleaned RNA counts
library(scDblFinder)
library(Seurat)
find_doublets <- function(sobj){
    query = scDblFinder(LayerData(sobj, layer='counts'))
    sobj$scDblFinder.score=query$scDblFinder.score
    sobj$scDblFinder.class=query$scDblFinder.class
    return(sobj)
}
SARC_f_list=lapply(SARC_f_list, find_doublets)
```

# Create Seurat for tumor biopsies
```{r}
tumor <- SARC_f_list[[3]]
for (i in 2:length(SARC_f_list)) {
  sample_name <- names(SARC_f_list)[i]  # Get the name of the current list element
  if (grepl("hSC26|hSC81_t|hSC92_t", sample_name)) { #get tumor biopsies and hSC26 sample
    print(paste0("Adding: ", sample_name))
    tumor <- merge(tumor, y = SARC_f_list[[i]])
    gc()  # Optional: Call garbage collection to manage memory
  }
}
```

# Create Seurat for PDSC (p0/p4)
```{r}
PDSC <- SARC_f_list[[1]]
for (i in 2:length(SARC_f_list)) {
  sample_name <- names(SARC_f_list)[i]  # Get the name of the current list element
  if (grepl("_p0|_p4", sample_name)) { #get PDSC samples
    print(paste0("Adding: ", sample_name))
    PDSC <- merge(PDSC, y = SARC_f_list[[i]])
    gc()  # Optional: Call garbage collection to manage memory
  }
}
```

## Save objects
```{r}
saveRDS(PDSC, "/home/caminors/Desktop/sc_RNAseq/QC_seurats/SARC_PDSC_f_Soup_doublet.rds")
saveRDS(tumor, "/home/caminors/Desktop/sc_RNAseq/QC_seurats/SARC_Tumor_f_Soup_doublet.rds")
```


# Gruel removal of doublets!
```{r}
Gruel_f_list = readRDS("/home/caminors/Desktop/sc_RNAseq/QC_seurats/Gruel_f_list_SoupX.rds")
## find doublets on cleaned RNA counts
library(scDblFinder)
library(Seurat)
find_doublets <- function(sobj){
    query = scDblFinder(LayerData(sobj, layer='counts'))
    sobj$scDblFinder.score=query$scDblFinder.score
    sobj$scDblFinder.class=query$scDblFinder.class
    return(sobj)
}
Gruel_f_list=lapply(Gruel_f_list, find_doublets)
```
```{r}
Gruel <- Gruel_f_list[[1]]
for (i in 2:length(Gruel_f_list)) {
  sample_name <- names(Gruel_f_list)[i]  # Get the name of the current list element
    print(paste0("Adding: ", sample_name))
    Gruel <- merge(Gruel, y = Gruel_f_list[[i]])
    gc()  # Optional: Call garbage collection to manage memory
}
```
## Save objects
```{r}
saveRDS(Gruel, "/home/caminors/Desktop/sc_RNAseq/QC_seurats/Gruel_f_Soup_doublet.rds")
```
